version: 2

models:
  - name: dim_date
    description: "Date dimension. Used to join with fact tables via the date_key column."
    columns:
      - name: date_key
        description: "Date key in YYYYMMDD format (e.g., 20250101)"
        tests:
          - unique
          - not_null

      - name: date_day
        description: "Actual date value (DATE type)"

      - name: year
        description: "Year (e.g., 2025)"

      - name: month
        description: "Month number (1–12)"

      - name: day
        description: "Day of the month (1–31)"

      - name: quarter
        description: "Quarter of the year (1–4)"

      - name: week
        description: "Week number in the year (1–53)"

      - name: is_weekend
        description: "TRUE if the date falls on a Saturday or Sunday"
